# Use root/example as user/password credentials
version: '3.1'

services:
  mongo:
    container_name: mongo-serv
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: administrator
      MONGO_INITDB_ROOT_PASSWORD: v2t1D7X3Gj
 
  mongo-express:
    container_name: mongo-express-serv
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: administrator
      ME_CONFIG_MONGODB_ADMINPASSWORD: v2t1D7X3Gj
      ME_CONFIG_MONGODB_URL: mongodb://administrator:v2t#1&D7X3Gj@mongo-serv:27017
